add_newline = false

[cmd_duration]
show_milliseconds = true

[git_metrics]
disabled = false

[golang]
disabled = true

[jobs]
threshold = 1

[kubernetes]
disabled = false

[memory_usage]
disabled = false

[shlvl]
disabled = false
# threshold = 1

[status]
disabled = false
