insecure-entitlements = [ "network.host", "security.insecure" ]

[worker.oci]
  gc = true
  reservedSpace = "50GB"
  maxUsedSpace = "350GB"
  minFreeSpace = "50GB"

[registry."docker.io"]
  mirrors = ["127.0.0.1:5000"]
  http = true
  insecure = true
[registry."registry.k8s.io"]
  mirrors = ["127.0.0.1:5001"]
  http = true
  insecure = true
[registry."gcr.io"]
  mirrors = ["127.0.0.1:5002"]
  http = true
  insecure = true
[registry."ghcr.io"]
  mirrors = ["127.0.0.1:5003"]
  http = true
  insecure = true
[registry."127.0.0.1"]
  mirrors = ["127.0.0.1:5010"]
  http = true
  insecure = true
